[package]
name = "rust-utility-tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"
uuid = { version = "1.16.0", features = ["v4", "v7", "js"] }
